//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class CommonProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommonProperties defaultInstance = ((CommonProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommonProperties())));
        
        public static CommonProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int groupMargin {
            get {
                return ((int)(this["groupMargin"]));
            }
            set {
                this["groupMargin"] = value;
            }
        }
    }
}
