//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class NVRAccessProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static NVRAccessProperties defaultInstance = ((NVRAccessProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NVRAccessProperties())));
        
        public static NVRAccessProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string HTTP_HEADER {
            get {
                return ((string)(this["HTTP_HEADER"]));
            }
            set {
                this["HTTP_HEADER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.124")]
        public string NVR_IP {
            get {
                return ((string)(this["NVR_IP"]));
            }
            set {
                this["NVR_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string NVR_USER_NAME {
            get {
                return ((string)(this["NVR_USER_NAME"]));
            }
            set {
                this["NVR_USER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tjxldnpdj2018!")]
        public string NVR_USER_PW {
            get {
                return ((string)(this["NVR_USER_PW"]));
            }
            set {
                this["NVR_USER_PW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://")]
        public string RTSP_HEADER {
            get {
                return ((string)(this["RTSP_HEADER"]));
            }
            set {
                this["RTSP_HEADER"] = value;
            }
        }
    }
}
